In [9]:
from matplotlib import pyplot as plt
import numpy as np

## Example 1:

Given the function 
$$f(x)=x^3-x^2+1$$
answer the following:

1. Evaluate f(2).


2. Evaluate f(2+h) for h =1,h=0.1 and h=0.01


3. Evaluate 
$$\frac{f(2+h)-f(2)}{h}$$
 for each of the $h$ values given above.
 
 
4. Hence estimate $\frac{df}{dx}(2)$.

#### Part 1

* First we __define__ a Pytyhon function to represent $f(x)$, as follows:

In [10]:
def f(x):
    return x**3-x**2+1

* Now we evaualuate $f(2)$ using the function we just defined: 

In [11]:
f(2)

5

#### Part 2

* We create a vector to represent the values of $h$ as follows:

In [12]:
h=np.array([1.0,0.1,0.01])
h

array([1.  , 0.1 , 0.01])

* Now we evaluate the function $f(2+h)$ using $f$ and $h$ from above:

In [13]:
f(2+h)

array([19.      ,  5.851   ,  5.080501])

#### Part 3

* Now we can use the $f$ and $h$ defined above to evaluate the ratio $\frac{f(2+h)-f(2)}{2}$.

In [14]:
(f(2+h)-f(2))/h

array([14.    ,  8.51  ,  8.0501])

#### Part 4

* It appears that as $h\to0$ then $\frac{f(2+h)-f(2)}{2}\to 8$, and we estimate

$$\frac{df}{dx}(2)\approx8.$$