# Engineering Maths 8.2

## Python Workbook 1

## Numerical Derivatives

In [0]:
from matplotlib import pyplot as plt
import numpy as np

* In this workbook we outline how to define a function using Pyhton.


* To begin, we must run the cell above containing __from matplotlib__ etc.


* To run the cell, hover the mouse over the square brackets, at which point a __play button__ appears. Press this to run the cell.

* When this is run for the first time a security notice may appear. You should press __Run Anyway__.


* This has imported some useful numerical function whic hmay be handy later on.


* Ther are 2 types of cells in these workbooks.
  1. __Markdown__ These cells appear as normal text. This cell is a Markdown cell.

  2. __Python__ The python cells appear as grey cells. These are the cells where the python code is actualy entered and run.

## Example 1:

Given the function 
$$f(x)=x^3-x^2+1$$
answer the following:

__(1)__ Evaluate f(2).

__(2)__ Evaluate f(2+h) for 

$$h =1,h=0.1 \text{ and } h=0.01$$


__(3)__ Evaluate 
$$\frac{f(2+h)-f(2)}{h}$$
 for each of the $h$ values given above.
 
 
__(4)__ Hence estimate $\frac{df}{dx}(2)$.

#### Part 1

* First we __define__ a Pytyhon function to represent $f(x)$, as follows:

In [0]:
def f(x):
    return x**3-x**2+1

* Now we evaualuate $f(2)$ using the function we just defined: 

In [3]:
f(2)

5

#### Part 2

* We create a vector to represent the values of $h$ as follows:

In [4]:
h=np.array([1.0,0.1,0.01])
h

array([1.  , 0.1 , 0.01])

* Now we evaluate the function $f(2+h)$ using $f$ and $h$ from above:

In [0]:
f(2+h)

array([19.      ,  5.851   ,  5.080501])

#### Part 3

* Now we can use the $f$ and $h$ defined above to evaluate the ratio $\frac{f(2+h)-f(2)}{2}$.

In [0]:
(f(2+h)-f(2))/h

array([14.    ,  8.51  ,  8.0501])

#### Part 4

* It appears that as $h\to0$ then $\frac{f(2+h)-f(2)}{2}\to 8$, and we estimate

$$\frac{df}{dx}(2)\approx8.$$

* If you want to add a new __Python cell__ to this workbook press the button __+Code__ above.


* If you want to add a new __Markdown cell__ to the workbook press the button __Text__ above.